### ISSUE TITLE
Possibility to integrate a custom logger

### ISSUE THREAD

**Issue by arditmezini** [proudmonkey/RESTApiResponseWrapper.Core#11]
Sometimes it's neccesary to log data for every request sent to the server.

**Comment by proudmonkey** [comment]
@arditmezini I agree and thank you for your suggestion. I will try to work on it on the next version or you could also contribute to this library and integrate those feature. :)

**Comment by enkodellc** [comment]
Custom Logger: https://github.com/salslab/AspNetCoreApiLoggingSample

I integrated both into my repository:  https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.Server/Middleware/APIResponseRequestLogginMiddleware.cs
