### ISSUE TITLE
How to return a File

### ISSUE THREAD

**Issue by ghost** [proudmonkey/RESTApiResponseWrapper.Core#13]
Hello! 
I've successfully implemented your package and everything works great! 
However, I'm now trying to serve some images from a folder, with the following code in the controller:
`public async Task<IActionResult> get_profile_image(string folder_name, string asset_path){
			var image = System.IO.File.OpenRead(Path.Combine(Directory.GetCurrentDirectory(),"assets", "profile", folder_name, asset_path));
			return File(image, "image/jpeg");
		}`

But that generates an exception: "Timeouts are not supported on this stream."

When I remove the middleware (by commenting the line app.UseAPIResponseWrapperMiddleware(); in Startup.cs), the image is successfully returned.

It makes me believe the reason is that the middleware is trying to serialize the stream/file. But I don't know how to solve this situation.

How can I set the middleware to "ignore" these jpeg files and return them the way they are?

Thank you very much!

**Comment by ghost** [comment]
Sorry, I found the solution!
It was solved by making the middleware usage conditional.

app.UseWhen(context => !context.Request.Path.StartsWithSegments("/assets"), appBuilder =>
{
      appBuilder.UseAPIResponseWrapperMiddleware();
});

**Comment by proudmonkey** [comment]
@Echeverrya Thank you for using this library on your project. If you are using .NET Core 3.x versions, I would recommend you to use AutoWrapper instead: https://github.com/proudmonkey/AutoWrapper

AutoWrapper is a new port of this library which is designed to support .NET Core 2.1, 2.2 and 3.x . The implementation of AutoWrapper was refactored to provide a more convenient way to use the middleware with added flexibility. Check it out! :)

This library is no longer maintained and obsolete.
