### ISSUE TITLE
About the single Object Return

### ISSUE THREAD

**Issue by anudwigna** [proudmonkey/RESTApiResponseWrapper.Core#2]
While trying to return a list, it works fine but when I try to return a single object, the response is not formatted properly.
Similarly, can i format the response to use camelcase?

THE RESPONSE: 
{"Version":null,"StatusCode":0,"Message":null} Caption Head","captionBody":null,"navigateUrl":null,"articleId":0}

THE ACTION:
`[HttpGet("{id}")]
        public ActionResult<Slider> Get(int id)
        {
            //APIResponse response = new APIResponse(200, "Hello") { Result = new Slider() { Id = 34 } };
            return new Slider() { Id = 23, CaptionHead = "Test Caption Head" };
        }`

**Comment by proudmonkey** [comment]
Hi, Thank you for trying out the library ;)

Can you please send a sample format for single object result?

**Comment by anudwigna** [comment]
@proudmonkey Thanks for the reply.

Here is my action
`[HttpGet("{id}")]
        public ActionResult<Slider> Get(int id)
        {
            //APIResponse response = new APIResponse(200, "Hello") { Result = new Slider() { Id = 34 } };
            Slider slider = new Slider();
            slider.ArticleId = 12;
            slider.CaptionBody = "Caption Body";
            slider.CaptionHead = "Caption  Head";
            slider.Id = 1;
            slider.UrlToImage = "URL TO Image!!!";
            slider.NavigateUrl = "Navigate URL";
            return slider;
        }`

Here is the response:
`{"Version":null,"StatusCode":0,"Message":null}nHead":"Caption  Head","captionBody":"Caption Body","navigateUrl":"Navigate URL","articleId":12}`

The response in which I am returning the Object is malformed. But when I return a list, the response is perfect.

**Comment by proudmonkey** [comment]
You need to return the APIResponse object when returning a custom object. For example:

`
[HttpGet("{id}")] 
	public APIResponse Get(int id) { 
		Slider slider = new Slider {
		    slider.ArticleId = 12, 
			slider.CaptionBody = "Caption Body",
			slider.CaptionHead = "Caption Head",
			slider.Id = 1,
			slider.UrlToImage = "URL TO Image!!!",
			slider.NavigateUrl = "Navigate URL"
		};
		return new APIResponse(200, "Hello", slider) ;
    }
`

**Comment by anudwigna** [comment]
@proudmonkey thank you for the reply. But can you explain why we need response object when returning the object.
And what about camel casing the fields of api response object

**Comment by proudmonkey** [comment]
@anudwigna because the APIResponse object contains the information to provide consistency. Here's an article demonstrating how it works: https://www.codeproject.com/Articles/1267008/ASP-NET-Core-2-1-Integrating-VMD-RESTApiResponseWr

**Comment by Atario** [comment]
I hit this issue too, just trying to return a normal object, no custom APIResponse.

Example:  if I download your sample solution from the above page, and change this method to this:

        // GET api/bands/7
        [HttpGet("{id}")]
        public Band Get(int id)
        {
            var data = SampleData.GetBands().Where(o => o.Id.Equals(id));
            if (data.Any())
                return data.First();

            return null;
        }

Just taking out the custom response, the normal object being returned.  Going to `/api/v1/bands/3` gives this response:

    {
        "Version": null,
        "StatusCode": 0,
        "Message": null
    }

Whereas if I change it to this:

        // GET api/bands/7
        [HttpGet("{id}")]
        public Band[] Get(int id)
        {
            var data = SampleData.GetBands().Where(o => o.Id.Equals(id));
            if (data.Any())
                return new Band[] { data.First() };

            return null;
        }

I get this:

    {
        "Version": "1.0.0.0",
        "StatusCode": 200,
        "Message": "Request successful.",
        "Result": [
            {
                "id": 3,
                "name": "Pearl Jam",
                "genre": "Grunge"
            }
        ]
    }

Things get messier if the object returned is more complicated, up to and including malformed JSON.

**Comment by proudmonkey** [comment]
Closing this. Please use AutoWrapper moving forward: https://github.com/proudmonkey/AutoWrapper
