### ISSUE TITLE
Success Status codes other then 200 are not handled

### ISSUE THREAD

**Issue by ajaybommena** [proudmonkey/RESTApiResponseWrapper.Core#3]
"Version": "1.0.0.0",
    "StatusCode": 201,
    "Message": "Unable to process the request.",
    "ResponseException": {
        "IsError": true,
        "ExceptionMessage": "Your request cannot be processed. Please contact a support.",
        "Details": null,
        "ReferenceErrorCode": null,
        "ReferenceDocumentLink": null,
        "ValidationErrors": null
    }

ExceptionMessage is shown for 201 created status.

Please correct me if I am wrong

**Comment by proudmonkey** [comment]
How are you returning a 201? You should have something like this:

`return new APIResponse(201,"Created");`

**Comment by ajaybommena** [comment]
No I am not using APIResponse. However, If I use APIResponse I am getting the right result.
Somehow I don't want to use any

**Comment by ajaybommena** [comment]
Thanks for the solution. If possible, can you please also provide a sample project which demonstrates all features available.

**Comment by proudmonkey** [comment]
That's noted. I'll work on a sample project. Thanks!

**Comment by proudmonkey** [comment]
Here's an article demonstrating how to use it in your application: https://www.codeproject.com/Articles/1267008/ASP-NET-Core-2-1-Integrating-VMD-RESTApiResponseWr
