### ISSUE TITLE
Support Net Core 2.1

### ISSUE THREAD

**Issue by jvargasipince** [proudmonkey/RESTApiResponseWrapper.Core#4]
Hi, I was using this library to Wrapper my response Api. Now, I'm working in a new Project in Net Core 2.1, but I can't install this because is not compatible. 

There are some alternative or configuration about this problem?

P.D => This is the error that i recieve when I try to install from Nugget Package

 NU1202: Package VMD.RESTApiResponseWrapper.Core 1.0.3 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). 
Package VMD.RESTApiResponseWrapper.Core 1.0.3 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0)

Thanks for help me.

**Comment by proudmonkey** [comment]
Thanks for your interest on this API. I surely will update the code to support the latest .NET Core version.

**Comment by proudmonkey** [comment]
Version 1.0.4 is now available for use in .NET Core 2.1 version. See it here: https://www.nuget.org/packages/VMD.RESTApiResponseWrapper.Core/1.0.4
