### ISSUE TITLE
How to return ModelStateErrors

### ISSUE THREAD

**Issue by vinayaroraincedo** [proudmonkey/RESTApiResponseWrapper.Core#5]
Hi,

I'm sending validation errors like below but enable to send using your middlerware. How to return ModelStateErros?
Sample response
{
"ActivationCode": [
  "Your profile already has been validated."
],
}
 return BadRequest(ModelState);

Error which is getting using your middleware.

There was an error parsing JSON data

Unexpected token { in JSON at position 63

**Comment by proudmonkey** [comment]
You need to throw the error like this:

`throw new ApiException("Your Message",401, ModelStateExtension.AllErrors(ModelState));`
