### ISSUE TITLE
Hi, Can you please provide a sample function which can return ApiError, ApiException, APIResponse, ValidationError?

### ISSUE THREAD

**Issue by vinayaroraincedo** [proudmonkey/RESTApiResponseWrapper.Core#6]
Hi,
Can you please provide a sample function which can return ApiError, ApiException, APIResponse, ValidationError?

**Comment by proudmonkey** [comment]
Yes. I will work on an article highlighting how to use this wrapper for any possible scenarios. I'll keep you posted. Thank you.

**Comment by proudmonkey** [comment]
Here you go: https://www.codeproject.com/Articles/1267008/ASP-NET-Core-2-1-Integrating-VMD-RESTApiResponseWr

**Comment by enkodellc** [comment]
For anyone looking for an example I have integrated this code into my repository:  https://github.com/enkodellc/blazorboilerplate

@proudmonkey  thanks for sharing!

**Comment by proudmonkey** [comment]
@enkodellc this is cool! It's good to see that you've integrated this to your project. :)
