### ISSUE TITLE
Won't wrap some error messages

### ISSUE THREAD

**Issue by selstam** [proudmonkey/RESTApiResponseWrapper.Core#7]
Hi!

Having problems when returning a response when binding the request object.

For example, if I do a HTTP Post without a body I get an error message saying "A non-empty request body is required." and that is all fine, that is correct. But the output is not correct in the response:

`
{
	"": [
		"A non-empty request body is required."
	]
}{
	"ApiVersion": "1.0.0.0",
	"CorrelationId": "51e7b9e6-0695-44db-af08-f8ab44a8c253",
	"StatusCode": 400,
	"Message": "Unable to process the request.",
	"ResponseException": {
		"IsError": true,
		"ExceptionMessage": "Your request cannot be processed. Please contact a support.",
		"Details": null,
		"ReferenceErrorCode": null,
		"ReferenceDocumentLink": null,
		"ValidationErrors": null
	}
}
`

As you can see the buffer is not overwritten but rather appended to the previous error.

What did I miss?

**Comment by proudmonkey** [comment]
Hi selstam.

Can you please provide the your POST curl? Also, for POST without payload, can you try passing a header Content-Length:0

**Comment by selstam** [comment]
Sure!

`C:\>curl -X POST "https://localhost:44356/api/HeartBeat" -H "accept: text/plain" -H "Content-Type: application/json-patch+json" -d ""`

`{"":["A non-empty request body is required."]}{"ApiVersion":"1.0.0.0","CorrelationId":"bb1dfd35-3e9c-40d3-8243-71c5edfd2068","StatusCode":400,"Message":"Unable to process the request.","ResponseException":{"IsError":true,"ExceptionMessage":"Your request cannot be processed. Please contact a support.","Details":null,"ReferenceErrorCode":null,"ReferenceDocumentLink":null,"ValidationErrors":null}}`

**Comment by selstam** [comment]
`C:\>curl -X POST "https://localhost:44356/api/HeartBeat" -H "accept: text/plain" -H "Content-Type: application/json-patch+json" -H "Content-Length: 0" -d ""`

`{"":["A non-empty request body is required."]}{"ApiVersion":"1.0.0.0","CorrelationId":"18b613be-583d-46e5-8ec4-83780178f301","StatusCode":400,"Message":"Unable to process the request.","ResponseException":{"IsError":true,"ExceptionMessage":"Your request cannot be processed. Please contact a support.","Details":null,"ReferenceErrorCode":null,"ReferenceDocumentLink":null,"ValidationErrors":null}}`

**Comment by selstam** [comment]
Actually it seems like it's the Content-Length that triggers it. If I send `-d "{}"` it works ... but of course it doesn't work if I also set content-length to zero.

**Comment by proudmonkey** [comment]
I'm just curious. Why just use a GET instead of POST? Is there any specific reasons?

**Comment by selstam** [comment]
No, not really. This came up during a test scenario ... But if someone makes a POST without a body I'd expect the same kind of error message as any other error. I'm not that familiar with swapping out streams and how that works withing the asp.net request pipeline but I'd assume you have to close the "old" response stream and replace it with a new one in this case ...

**Comment by proudmonkey** [comment]
> I'm not that familiar with swapping out streams and how that works withing the asp.net request pipeline but I'd assume you have to close the "old" response stream and replace it with a new one in this case ...

In the context of ASP.NET Core, That's correct.
