### ISSUE TITLE
Something seems broken with the JSON serialization generally

### ISSUE THREAD

**Issue by Atario** [proudmonkey/RESTApiResponseWrapper.Core#9]
I took [the example project](https://www.codeproject.com/Articles/1267008/ASP-NET-Core-2-1-Integrating-VMD-RESTApiResponseWr) and added this controller method:

        // GET: api/bands/test
        [HttpGet("test")]
        public APIResponse Test()
        {
            var res = new APIResponse(500, "Not OK");
            res.ResponseException = new ApiError("Hi There")
            {
                Details = @"
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string
                        This is a long string",
                ReferenceDocumentLink = @"http://www.example.com/this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link"
            };
            return res;
        }

and I got this response:

    {"Version":"1.0.0.0","StatusCode":500,"Message":"Request responded with exceptions.","ResponseException":{"IsError":true,"ExceptionMessage":"An unhandled error occurred.","Details":null,"ReferenceErrorCode":null,"ReferenceDocumentLink":null,"ValidationErrors":null}}s a long string\r\n                        This is a long string\r\n                        This is a long string\r\n                        This is a long string\r\n                        This is a long string\r\n                        This is a long string\r\n                        This is a long string\r\n                        This is a long string\r\n                        This is a long string","referenceErrorCode":null,"referenceDocumentLink":"http://www.example.com/this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link-this-is-a-long-link","validationErrors":null}}

Which seems garbled — it's not even valid JSON.  Am I just misunderstanding how to do this?

**Comment by proudmonkey** [comment]
That's not how you return an error message to the response. You need use the APIException object like this:

`throw new ApiException($"Your error message here", 400);`

500 status code is intended for unhandled errors, not handled.

**Comment by Atario** [comment]
I'm trying to return a stack trace inside the `Details` field.  I can't see any way of doing that…

**Comment by proudmonkey** [comment]
> 

I'm trying to return a stack trace inside the Details field. I can't see any way of doing that…
--

I will modify the code to toggle debug mode and display stack trace. For the time being, You have to fork the repo and uncomment the line that has:

`#if !DEBUG`

You can see it here:
https://github.com/proudmonkey/RESTApiResponseWrapper.Core/blob/master/VMD.RESTApiResponseWrapper.Core/APIResponseMiddleware.cs

**Comment by proudmonkey** [comment]
Closing this. Please use AutoWrapper moving forward: https://github.com/proudmonkey/AutoWrapper
